---
- name: Render env.yml.j2 using generated vars
  hosts: localhost
  gather_facts: false
  vars_files:
    - ./env.local.generated.yml
  tasks:
    - name: Ensure ~/.ansible/conf exists
      ansible.builtin.file:
        path: "{{ lookup('env','HOME') }}/.ansible/conf"
        state: directory
        mode: '0700'

    - name: Render full env.yml.j2 to user's ansible conf
      ansible.builtin.template:
        src: ../templates/env.yml.j2
        dest: "{{ lookup('env','HOME') }}/.ansible/conf/env.yml"
        mode: '0600'
        force: yes