- name: Load survey for Nutanix (if present)
	ansible.builtin.include_role:
  name: integration_survey_loader
	run_once: true
	delegate_to: localhost

- name: include install.yml
- ansible.builtin.import_tasks: install.yml
- name: include configure.yml
- ansible.builtin.import_tasks: configure.yml
- name: include test.yml
- ansible.builtin.import_tasks: test.yml
- name: include backup.yml
- ansible.builtin.import_tasks: backup.yml
- name: include restore.yml
- ansible.builtin.import_tasks: restore.yml
