---
galaxy_info:
  author: "Red Hat Management"
  description: "Integration - Product integration_generic ansible_dev_node_orchestration and configuration"
  company: "Red Hat"
  license: "Apache-2.0"
  min_ansible_version: "2.10"
  max_ansible_version: "2.16"
  platforms:
    - name: EL
      versions:
        - "9"
        - "10"
  categories:
    - ansible_dev_node_orchestration
    - system

dependencies: []
