---
# handlers for OpenShift role

- name: "Restart OpenShift API"
  ansible.builtin.service:
    name: "openshift-api"
    state: "restarted"
  listen: "restart openshift api"

- name: "Restart OpenShift Controller"
  ansible.builtin.service:
    name: "openshift-controller-manager"
    state: "restarted"
  listen: "restart openshift controller"

- name: "Restart OpenShift Scheduler"
  ansible.builtin.service:
    name: "openshift-scheduler"
    state: "restarted"
  listen: "restart openshift scheduler"

- name: "Reload OpenShift Configuration"
  ansible.builtin.service:
    name: "openshift"
    state: "reloaded"
  listen: "reload openshift config"
