controller_hostname: https://aap.example.com
controller_inventory_name: Infra Inventory
controller_org: Default
controller_password: r3dh4t7!
controller_project_branch: main
controller_project_name: RedHat_Management
controller_project_scm_url: ''
controller_username: admin
controller_validate_certs: false
inventory_sources:
  - name: aap
    script_name: dynamic_inventory_aap.py
    script_path: plugins/dynamic_inventory_aap.py
    type: custom_script
  - name: foreman
    script_name: dynamic_inventory_foreman.py
    script_path: plugins/dynamic_inventory_foreman.py
    type: custom_script
  - name: insights
    script_name: dynamic_inventory_insights.py
    script_path: plugins/dynamic_inventory_insights.py
    type: custom_script
  - name: libvirt
    script_name: dynamic_inventory_libvirt.py
    script_path: plugins/dynamic_inventory_libvirt.py
    type: custom_script
  - name: nutanix
    script_name: dynamic_inventory_nutanix.py
    script_path: plugins/dynamic_inventory_nutanix.py
    type: custom_script
  - name: satellite
    script_name: dynamic_inventory_satellite.py
    script_path: plugins/dynamic_inventory_satellite.py
    type: custom_script
  - name: servicenow_
    script_name: dynamic_inventory_servicenow_.py
    script_path: plugins/dynamic_inventory_servicenow_.py
    type: custom_script
  - name: splunk
    script_name: dynamic_inventory_splunk.py
    script_path: plugins/dynamic_inventory_splunk.py
    type: custom_script
  - name: vmware
    script_name: dynamic_inventory_vmware.py
    script_path: plugins/dynamic_inventory_vmware.py
    type: custom_script
