---
- ansible.builtin.import_tasks: install.yml
- ansible.builtin.import_tasks: configure.yml
- ansible.builtin.import_tasks: test.yml
- ansible.builtin.import_tasks: backup.yml
- ansible.builtin.import_tasks: restore.yml
