---
galaxy_info:
  author: "Red Hat Management"
  description: "Legacy - Legacy ansible_dev_node_support and backward compatibility"
  company: "Red Hat"
  license: "Apache-2.0"
  min_ansible_version: "2.10"
  max_ansible_version: "2.16"
  platforms:
    - name: EL
      versions:
        - "9"
        - "10"
  categories:
    - system

dependencies: []
