aap_project_name: "LVM Automation Project"
aap_project_description: "Project for LVM automation playbooks"
aap_project_scm_type: "git"
aap_project_scm_url: "https://git.example.com/yourrepo.git"
aap_project_scm_branch: "main"
aap_project_playbooks:
  - disk_integration.yml
  - lvm_auto_extend.yml
  - lvm_health_check.yml
  - nutanix_inventory.yml
  - servicenow_inventory.yml
  - satellite_inventory.yml
  - insights_inventory.yml