---
galaxy_info:
  author: Red Hat Management Team
  description: Configure network infrastructure for RHIS - subnets, DHCP, DNS
  company: Red Hat
  license: Apache-2.0
  min_ansible_version: "2.10"
  galaxy_tags:
    - network
    - dhcp
    - dns
    - provisioning
    - infrastructure
    - libvirt
    - kvm
    - automation

dependencies: []
