---
galaxy_info:
  author: Red Hat Management Team
  description: Configure network platform_infrastructure_core for RHIS - subnets, DHCP, DNS
  company: Red Hat
  license: Apache-2.0
  min_ansible_version: "2.10"
  galaxy_tags:
    - network
    - dhcp
    - dns
    - platform-provisioning
    - platform-infrastructure-core
    - libvirt
    - kvm
    - automation
