---
galaxy_info:
  author: "Red Hat Management"
  description: "OpenShift 4.21 Deployment - Deploy OpenShift Container Platform"
  company: "Red Hat"
  license: "Apache-2.0"
  min_ansible_version: "2.10"

  platforms:
    - name: EL
      versions:
        - "9"
        - "10"
  galaxy_tags:
    - cloud
    - container
