nutanix_inventory_name: "Nutanix Inventory"
nutanix_project_name: "Nutanix Project"
nutanix_inventory_path: "inventories/nutanix"
organization_name: "Default"
aap_controller_host: "https://aap.example.com"
aap_controller_username: "admin"
aap_controller_password: "password"
aap_controller_verify_ssl: false