---
- name: Create Nutanix credential in AAP
  awx.awx.credential:
- name: "Nutanix Prism Credential"
    description: "Credentials for Nutanix Prism Central"
    organization: "{{ organization_name }}"
    credential_type: "Nutanix Prism"
    inputs:
    host: "{{ nutanix_host }}"
    username: "{{ nutanix_username }}"
    password: "{{ vault_nutanix_password }}"
    port: "{{ nutanix_port }}"
    validate_certs: "{{ nutanix_validate_certs }}"
    controller_host: "{{ aap_controller_host }}"
    controller_username: "{{ aap_controller_username }}"
    controller_password: "{{ vault_aap_controller_password }}"
    controller_validate_certs: "{{ aap_controller_verify_ssl }}"
    state: present
