galaxy_info:
  author: "Red Hat Infrastructure Standard"
  description: "RHIS Main Orchestration Role"
  company: "Red Hat"
  license: "Apache License 2.0"
  min_ansible_version: "2.9"
  
  galaxy_tags:
    - "orchestration"
    - "rhis"
    - "red-hat"
    - "satellite"
    - "aap"
    - "idm"
    - "openshift"

dependencies:
  - { role: "configuration_manager" }
  - { role: "deployment_setup" }
  - { role: "infrastructure_manager" }
  - { role: "inventory_generator" }
  - { role: "integration" }
  - { role: "cmdb" }
  - { role: "support" }
