---
# Default variables for ansible_dev_node_orchestration_master role
ansible_dev_node_orchestration_master_orchestration_master_enabled: true
ansible_dev_node_orchestration_master_orchestration_master_version: "1.0"
ansible_dev_node_orchestration_master_orchestration_master_timeout: 86400
ansible_dev_node_orchestration_master_orchestration_master_max_retries: 10

# Supported scenarios
ansible_dev_node_orchestration_master_deploy_infrastructure: true
ansible_dev_node_orchestration_master_configure_os: true
ansible_dev_node_orchestration_master_deploy_products: true
ansible_dev_node_orchestration_master_run_tests: true

# Feature toggles
ansible_dev_node_orchestration_master_configure_aap_rbac: true
ansible_dev_node_orchestration_master_configure_satellite_api: true
ansible_dev_node_orchestration_master_configure_satellite_content: true
ansible_dev_node_orchestration_master_deploy_idm_replicas: false
