---
galaxy_info:
  author: RedHat Management
  description: Generic product backup ansible_dev_node_orchestration role
  company: RedHat
  license: GPL-3.0-or-later
  min_ansible_version: '2.9'
  galaxy_tags:
    - backup
    - disaster-recovery
    - lifecycle

dependencies: []
