---
# Role: rhis_aap_controller_setup
# Purpose: Configure AAP controller (manifest, auth, certificates)
# This role sets up the AAP controller instance with licenses, authentication,
# and service certificates before deployment.

- name: "Fetch manifest from CDN"
  ansible.builtin.include_tasks: fetch_manifest.yml
  tags:
    - rhis_controller_manifest
    - rhis_controller_setup

- name: "Add AAP manifest to controller"
  ansible.builtin.include_tasks: add_aap_manifest.yml
  tags:
    - rhis_controller_manifest
    - rhis_controller_setup

- name: "Configure service certificate"
  ansible.builtin.include_tasks: add_service_certificate.yml
  tags:
    - rhis_controller_certificate
    - rhis_controller_setup

- name: "Configure AAP authentication settings"
  ansible.builtin.include_tasks: configure_aap_auth.yml
  tags:
    - rhis_controller_auth
    - rhis_controller_setup
