---
- name: Add Nutanix inventory source
  import_tasks: nutanix_inventory.yml

- name: Add Insights inventory source
  import_tasks: insights_inventory.yml

- name: Add ServiceNow inventory source
  import_tasks: servicenow_inventory.yml

- name: Add Satellite inventory source
  import_tasks: satellite_inventory.yml