---
- name: Create Nutanix inventory source in AAP
  awx.awx.inventory_source:
- name: "Nutanix Inventory"
    inventory: "{{ nutanix_inventory_name }}"
    source: scm
    source_project: "{{ nutanix_project_name }}"
    source_path: "{{ nutanix_inventory_path }}"
    organization: "{{ organization_name }}"
    controller_host: "{{ aap_controller_host }}"
    controller_username: "{{ aap_controller_username }}"
    controller_password: "{{ aap_controller_password }}"
    validate_certs: "{{ aap_controller_verify_ssl }}"
    state: present