---
- name: Create Satellite inventory source in AAP
  awx.awx.inventory_source:
- name: "Satellite Inventory"
    inventory: "{{ satellite_inventory_name }}"
    source: satellite6
    organization: "{{ organization_name }}"
    controller_host: "{{ aap_controller_host }}"
    controller_username: "{{ aap_controller_username }}"
    controller_password: "{{ aap_controller_password }}"
    validate_certs: "{{ aap_controller_verify_ssl }}"
    state: present