---
- name: Create ServiceNow inventory source in AAP
  awx.awx.inventory_source:
- name: "ServiceNow Inventory"
    inventory: "{{ servicenow_inventory_name }}"
    source: servicenow
    organization: "{{ organization_name }}"
    controller_host: "{{ aap_controller_host }}"
    controller_username: "{{ aap_controller_username }}"
    controller_password: "{{ aap_controller_password }}"
    validate_certs: "{{ aap_controller_verify_ssl }}"
    state: present