---
galaxy_info:
  author: Red Hat Management Team
  description: Configure Satellite 6.18 provisioning templates and kickstart files for RHEL 9 & 10
  company: Red Hat
  license: Apache-2.0
  min_ansible_version: "2.10"
  galaxy_tags:
    - satellite
    - kickstart
    - provisioning
    - rhel
    - rhel9
    - rhel10
    - automation
    - rhis

dependencies: []
