---
# Servicenow Ticket Management Defaults

servicenow_instance: "https://dev.servicenow.com"
servicenow_username: "admin"
servicenow_password: "password"
servicenow_table: "incident"
servicenow_ticket_short_description: "Automated LVM Alert"
servicenow_ticket_description: "Disk or LVM event detected by automation."
servicenow_ticket_category: "Infrastructure"
servicenow_ticket_impact: "2"         # 1=High, 2=Medium, 3=Low
servicenow_ticket_urgency: "2"        # 1=High, 2=Medium, 3=Low
servicenow_ticket_assignment_group: "Linux Admins"
servicenow_ticket_caller_id: "automation"
servicenow_api_timeout: 30
servicenow_verify_ssl: false
