---
galaxy_info:
  author: Red Hat Management Team
  description: Configure Satellite 6.18 Operating Systems, Install Media, and Kickstart Repository
  company: Red Hat
  license: Apache-2.0
  min_ansible_version: "2.10"
  galaxy_tags:
    - scenario-satellite
    - os-generic
    - media
    - kickstart
    - platform-provisioning
    - rhel
    - rhel9
    - rhel10
    - automation
